### ISSUE TITLE
Authentication Controller Module

### ISSUE THREAD

**Issue by ittocean** [ittaiyam/PetBook#2]
Agent,

Your second task is to build a controller module that handles the third-party authenticated login requests.
To do so you will first edit the passport builder to include google OAuth2 strategy.
Once the strategy configuration is done you will be able to prefer the controller. The controller module creates and returns an express router to which you shall add the /google and /google/callback paths.
The function handling the login request who will be provided the user instance that is injected by the passport strategy, will use the provided user instance to return the logged in user's token in response.
You will also be required to create a new application via google developers to be provided with a client ID and secret and to be able to test that it all works.

Good luck!

**Comment by ittaiyam** [comment]
commit edefd7ed73c485487b50752e41827db3f0ad6f1f

**Comment by ittocean** [comment]
Commit edefd7ed73c485487b50752e41827db3f0ad6f1f
